# Generated by Django 4.0.2 on 2022-04-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
    ]
