version: "3.8"

services:
  web:
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 &&
             gunicorn -w 2 taxi_service.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  db:
    image: postgres:15
    env_file:
      - .env
#    environment:
#      POSTGRES_DB: taxi_db
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password

volumes:
  static_volume:
