version: "3.8"

services:
  web:
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py collectstatic --noinput --clear &&
             python manage.py migrate &&
             python manage.py create_test_superuser &&
             gunicorn -w 2 taxi_service.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  db:
    image: postgres:15
    env_file:
      - .env
    networks:
      - backend

volumes:
  static_volume:
networks:
  backend:
     driver: bridge
