version: "3.8"

services:
  web:
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py collectstatic --noinput --clear &&
             python manage.py migrate &&
             python manage.py create_test_superuser --username=test --email=test@gmail.com --password=123456 &&
             gunicorn -w 2 taxi_service.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  db:
    image: postgres:15
    env_file:
      - .env
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  static_volume:
networks:
  backend:
     driver: bridge
